# Generated by Django 5.2.2 on 2025-07-15 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_address_order_shipping_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
    ]
