# Generated by Django 5.2.2 on 2025-07-15 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_address_phone_remove_address_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created_at',
            new_name='order_date',
        ),
    ]
