# Generated by Django 5.2.2 on 2025-07-20 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_address_full_name_order_payment_proof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menudetail',
            name='menuID',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='MenuDetail',
        ),
    ]
