# Generated by Django 5.2.2 on 2025-07-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_menudetail_menuid_delete_menu_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdetail',
            old_name='productDetailName',
            new_name='availability',
        ),
        migrations.RemoveField(
            model_name='product',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='Information',
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='Reviews',
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='productDetailImage',
        ),
        migrations.AddField(
            model_name='productdetail',
            name='brand',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='color',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='condition',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='material',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='size',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
