# Generated by Django 5.2.2 on 2025-07-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_productdetailname_productdetail_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/Profile/'),
        ),
    ]
