# Generated by Django 5.2.2 on 2025-07-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_customer_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile/'),
        ),
    ]
